version: '2'
services:
   consul:
     container_name: consul
     build: .
     network_mode: host
     privileged: true
     ports:
       - 8300:8300
       - 8500:8500
     volumes:
       - "/consul:/consul"
     restart: always
     logging:
       driver: "json-file"
       options:
         max-size: 50m
         max-file: "2"
