version: '2'
services:
   consul:
     image: anchorfree/consul:latest
     container_name: consul
     network_mode: host
     privileged: true
     ports:
       - 8300:8300
       - 8500:8500
     volumes:
       - "/consul:/consul"
     restart: never
     logging:
       driver: "json-file"
       options:
         max-size: 50m
         max-file: "2"
